import = ["theme/darcula.toml", "shortcut/keyboard.toml"]

[window]
padding = { x = 15, y = 15 }
dynamic_padding = true
opacity = 0.95
class = { instance = "Alacritty", general = "Alacritty" }
decorations = "Full"
startup_mode = "Windowed"
dynamic_title = true


[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Medium" }
bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
italic = { family = "JetBrains Mono Nerd Font", style = "MediumItalic" }
bold_italic = { family = "JetBrains Mono Nerd Font", style = "Bold Italic" }
size = 12.0


[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "on" }
vi_mode_style = { shape = "Beam", blinking = "On" }
blink_interval = 600
blink_timeout = 5
unfocused_hollow = true
thickness = 0.3


[mouse]
hide_when_typing = true

[bell]
animation = "EaseOutExpo"
duration = 0
